steps:
  - name: gcr.io/cloud-builders/gsutil
    id: readCacheComposer
    args: ['-m','cp','-r', 'gs://cache-pipeline-cd/composer', '/workspace/']
  - name: "gcr.io/cloud-builders/docker"
    id: DependencesPhp
    args:
      - "run"
      - "-v"
      - "/workspace:/app"
      - "-v"
      - "/workspace/composer:/tmp"
      - "composer"
      - "composer"
      - "install"
      - "--ignore-platform-reqs"
      - "--prefer-dist"
    waitFor: ['readCacheComposer']
  - name: gcr.io/cloud-builders/gsutil
    id: writeCacheComposer
    args: ['-m','rsync', '-r', '/workspace/composer', 'gs://cache-pipeline-cd/composer']
    waitFor: ['DependencesPhp']
  - name: "gcr.io/cloud-builders/docker"
    id: CodeSniffer
    args:
      - "run"
      - "-v"
      - "/workspace:/app"
      - "composer"
      - "composer"
      - "cs-check"
    waitFor: ['DependencesPhp','writeCacheComposer']
  - name: "gcr.io/cloud-builders/docker"
    id: BuildTestImage
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/${_NAMESPACE}/${_DEPLOY}/tests:latest"
      - "-f"
      - "./docker/test/Dockerfile.test"
      - "."
    waitFor: ['DependencesPhp','CodeSniffer']
  - name: "gcr.io/cloud-builders/docker"
    id: PushTestImage
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/${_NAMESPACE}/${_DEPLOY}/tests:latest"
  - name: "gcr.io/cloud-builders/docker"
    id: TestCoverage
    args:
      - "run"
      - "-v"
      - "/workspace:/var/www/html"
      - "-v"
      - "/workspace/config/sample.env:/var/www/html/config/.env"
      - "--workdir"
      - "/var/www/html"
      - "gcr.io/$PROJECT_ID/${_NAMESPACE}/${_DEPLOY}/tests:latest"
      - "composer"
      - "test-coverage"
    waitFor: ['DependencesPhp','CodeSniffer','BuildTestImage','PushTestImage']
  - name: "gcr.io/cloud-builders/docker"
    id: GenerateSwagger
    args:
      - "run"
      - "-v"
      - "/workspace:/app"
      - "composer"
      - "composer"
      - "generate-swagger"
    waitFor: ['DependencesPhp','CodeSniffer','TestCoverage']
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/${_NAMESPACE}/${_DEPLOY}:$SHORT_SHA"
      - "-f"
      - "./docker/base/Dockerfile.base"
      - "."
    waitFor: ['DependencesPhp','CodeSniffer','TestCoverage','GenerateSwagger']
  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/${_NAMESPACE}/${_DEPLOY}:$SHORT_SHA"
  - name: "gcr.io/cloud-builders/kubectl"
    id: Deploy
    args:
      - "set"
      - "image"
      - "deploy"
      - "${_DEPLOY}"
      - "-n"
      - "${_NAMESPACE}"
      - "${_CONTAINER_NAME}=gcr.io/$PROJECT_ID/${_NAMESPACE}/${_DEPLOY}:$SHORT_SHA"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=${_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}"
