FROM debian:jessie

RUN apt-get update \
    && apt-get -y install \
    lsb-release \
    apt-transport-https \
    ca-certificates \
    wget \
    curl \
    && cp /usr/share/zoneinfo/Etc/GMT+3 /etc/localtime \
    && wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
    && echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php7.4.list \
    && apt-get update \
    && apt-get -y install php7.4 \
    php7.4-cli \
    php7.4-fpm \
    php7.4-json \
    php7.4-pdo \
    php7.4-mysql \
    php7.4-sqlite \
    php7.4-zip \
    php7.4-gd \
    php7.4-mbstring \
    php7.4-curl \
    php7.4-xml \
    php7.4-bcmath \
    php7.4-json \
    php7.4-intl \
    php-xdebug \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer \
    && apt-get clean
