repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: mixed-line-ending
        args: [--fix=lf]
        exclude: ^src/Financial/src/test/resources
    -   id: end-of-file-fixer
        exclude: ^src/Financial/src/test/resources
    -   id: trailing-whitespace
        exclude: ^src/Financial/src/test/resources
